Article {
  _id: ID
  title: String
  slug: String // autogenerated
  models: Person[]
  photos: URL[]
  date: {
    day: Number // 1..31
    month: Number // 1..12
    year: Number
  }
}

Person {
  _id: ID
  order: Number
  name: String
  slug: String // autogenerated
  gender: 0/1
  instagram: URL
  book: Photo[]
  polaroids: Photo[]
  params: {
    height: Number // cm
    chest: Number // cm
    waist: Number // cm
    hips: Number // cm
    shoe: Number // rus size
    hair: String
    eyes: String
  }
}

Photo {
  _id: ID
  fileName: String
  ratio: Number
}

Applications {
  _id: ID
  name: String
  city: String
  phone: String
  email: String
  social: URL
  photos: URL[]
  params: {
    height: Number
    chest: Number
    waist: Number
    hips: Number
    shoe: Number
    age: Number
  }
}
